class DomainError(Exception):
    pass


class UserNotFoundError(DomainError):
    pass
